#pragma config(UserModel, "/ports_setup.h")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "setup.c"
#include "misc_functions.c" 						// Contains all the miscellaneous functions
#include "sensing_functions.c" 						// Contains all the functions for sensing
#include "movement_functions.c" 					// Contains all the movement functions

int page = 1;
bool rightWasPressed = false;
bool leftWasPressed = false;
bool upWasPressed = false;
bool centerWasPressed = false;
bool downWasPressed = false;

bool rightPressed = false;
bool leftPressed = false;
bool upPressed = false;
bool centerPressed = false;
bool downPressed = false;

long textFile;

void writeToFile(string whatToWrite)
{
    fileWriteData(textFile, whatToWrite, strlen(whatToWrite));
}

void page1()
{
    // If the center button is pressed, write to the debug stream to move for relative degrees
    if (centerPressed)
    {
        // Sets the motor speeds based on the degrees traveled
        int leftSpeed = 0;
        int rightSpeed = 0;
        if (fabs(getRelDegrees(LEFT))>fabs(getRelDegrees(RIGHT)))
        {
            leftSpeed = 50*sgn(getRelDegrees(LEFT));
            rightSpeed = getRelDegrees(RIGHT)/getRelDegrees(LEFT)*leftSpeed;
        }
        else if (fabs(getRelDegrees(RIGHT))>fabs(getRelDegrees(LEFT)))
        {
            rightSpeed = 50*sgn(getRelDegrees(RIGHT));
            leftSpeed = getRelDegrees(LEFT)/getRelDegrees(RIGHT)*rightSpeed;
        }

        if (fabs(leftSpeed)<5)
        {
            leftSpeed = 0;
        }
        if (fabs(rightSpeed)<5)
        {
            rightSpeed = 0;
        }

        if (fabs(leftSpeed)>40)
        {
            leftSpeed = sgn(leftSpeed)*50;
        }

        if (fabs(rightSpeed)>40)
        {
            rightSpeed = sgn(rightSpeed)*50;
        }

        // Based on the speeds and how close they are, it determines if you were trying to turn for a nice amount of degrees or go straight etc.
        if (!(leftSpeed==0 && leftSpeed == 0))
        {
            playImmediateTone(100, 10);

            // Turning 1 motor with the right motor
            if (leftSpeed == 0)
            {
                float val = cmFromDeg(getRelDegrees(RIGHT)/2.0);

                // If it is close to a multiple of 90
                if (mod(angleFromCM(fabs(val)), 90) < 15 || mod(angleFromCM(fabs(val)), 90) > 75)
                {
                    writeDebugStreamLine("turn1Motor(%d, %d, RIGHT);", sgn(val)*50, 90*round(angleFromCM(val)/90.0));
                }
                else
                {
                    writeDebugStreamLine("turn1Motor(%d, %d, RIGHT);", sgn(val)*50, angleFromCM(val));
                }
            }

            // Turning 1 motor with the left motor
            else if (rightSpeed == 0)
            {
                float val = cmFromDeg(getRelDegrees(LEFT)/2.0);

                // If it is close to a multiple of 90
                if (mod(angleFromCM(fabs(val)), 90) < 15 || mod(angleFromCM(fabs(val)), 90) > 75)
                {
                    writeDebugStreamLine("turn1Motor(%d, %d, LEFT);", sgn(val)*50, 90*round(angleFromCM(val)/90.0));
                }
                else
                {
                    writeDebugStreamLine("turn1Motor(%d, %d, LEFT);", sgn(val)*50, angleFromCM(val));
                }
            }

            // Turning 2 motor
            else if (rightSpeed == -leftSpeed)
            {
                float val = cmFromDeg(getRelDegrees(LEFT));

                // If it is close to a multiple of 90
                if (mod(angleFromCM(fabs(val)), 90) < 15 || mod(angleFromCM(fabs(val)), 90) > 75)
                {
                    writeDebugStreamLine("turn2Motor(20, %d);", 90*round(angleFromCM(val)/90.0));
                }
                else
                {
                    writeDebugStreamLine("turn2Motor(20, %d);", angleFromCM(val));
                }
            }

            // Any other movement
            else
            {
                writeDebugStreamLine("moveSimpleAcc(%d, %d, %d, 0.2, RELDEG);", leftSpeed, rightSpeed, max2(fabs(getRelDegrees(RIGHT)),fabs(getRelDegrees(LEFT))));
            }
            resetRelative();
        }
    }

    // If the down button is pressed, write to the debug stream to wall square backwards
    else if (downPressed)
    {
        playImmediateTone(100, 10);
        writeDebugStreamLine("moveSimpleNone(-100, -100, 1000, TIME);");
        writeDebugStreamLine("sleep(50);");
        resetRelative();
    }
}

void page2()
{
    // If the up button is pressed, write to the debug steam to line square on the front edge
    if (upPressed)
    {
        playImmediateTone(100, 10);
        writeDebugStreamLine("lineSquare(53, 48, 2, 3, -0.4, -50, 1000);");
        writeDebugStreamLine("setSpeed(0, 0);");
        writeDebugStreamLine("sleep(100);");
        writeDebugStreamLine("resetRelative();");
        resetRelative();
    }

    // If the down button is pressed, write to the debug stream to line square on the back edge
    else if (downPressed)
    {
        playImmediateTone(100, 10);
        writeDebugStreamLine("lineSquare(53, 48, 2, 3, 0.4, 50, 1000);");
        writeDebugStreamLine("setSpeed(0, 0);");
        writeDebugStreamLine("sleep(100);");
        writeDebugStreamLine("resetRelative();");
        resetRelative();
    }
}

void page3()
{
    // If the up button is pressed, write to the debug stream to line follow on the left edge with sensor 2
    if (upPressed)
    {
        playImmediateTone(100, 10);
        writeDebugStreamLine("lineFollow(40, 30, %d, 50, 0.3, 0.23, 50, 2, RELDEG);", (getRelDegrees(LEFT)+getRelDegrees(RIGHT))/2);
        writeDebugStreamLine("resetRelative();");
        resetRelative();
    }

    // If the center button is pressed, write to the debug steam to move until sensor 2 sees a color
    else if (centerPressed)
    {
        // Sets the motor speeds based on the degrees traveled
        int leftSpeed = 0;
        int rightSpeed = 0;
        if (fabs(getRelDegrees(LEFT))>fabs(getRelDegrees(RIGHT)))
        {
            leftSpeed = 20*sgn(getRelDegrees(LEFT));
            rightSpeed = getRelDegrees(RIGHT)/getRelDegrees(LEFT)*leftSpeed;
        }
        else if (fabs(getRelDegrees(RIGHT))>fabs(getRelDegrees(LEFT)))
        {
            rightSpeed = 20*sgn(getRelDegrees(RIGHT));
            leftSpeed = getRelDegrees(LEFT)/getRelDegrees(RIGHT)*rightSpeed;
        }

        if (fabs(leftSpeed)<5)
        {
            leftSpeed = 0;
        }
        if (fabs(rightSpeed)<5)
        {
            rightSpeed = 0;
        }

        if (fabs(leftSpeed)>15)
        {
            leftSpeed = sgn(leftSpeed)*20;
        }

        if (fabs(rightSpeed)>15)
        {
            rightSpeed = sgn(rightSpeed)*20;
        }

        if (!(leftSpeed==0 && leftSpeed == 0))
        {
            playImmediateTone(100, 10);
            writeDebugStreamLine("moveSenseSimple(%d, %d, %s, 2, COLOR);", leftSpeed, rightSpeed, getColourName[getColor(2)]);
            resetRelative();
        }
    }

    // If the down button is pressed, write to the debug stream to line follow on the right edge with sensor 2
    else if (downPressed)
    {
        playImmediateTone(100, 10);
        writeDebugStreamLine("lineFollow(40, 30, %d, 50, -0.3, -0.23, 50, 2, RELDEG);", (getRelDegrees(LEFT)+getRelDegrees(RIGHT))/2);
        writeDebugStreamLine("resetRelative();");
        resetRelative();
    }
}

void page4()
{
    // If the up button is pressed, write to the debug stream to line follow on the left edge with sensor 3
    if (upPressed)
    {
        playImmediateTone(100, 10);
        writeDebugStreamLine("lineFollow(40, 30, %d, 50, 0.3, 0.23, 50, 3, RELDEG);", (getRelDegrees(LEFT)+getRelDegrees(RIGHT))/2);
        writeDebugStreamLine("resetRelative();");
        resetRelative();
    }

    // If the center button is pressed, write to the debug steam to move until sensor 3 sees a color
    else if (centerPressed)
    {
        // Sets the motor speeds based on the degrees traveled
        int leftSpeed = 0;
        int rightSpeed = 0;
        if (fabs(getRelDegrees(LEFT))>fabs(getRelDegrees(RIGHT)))
        {
            leftSpeed = 20*sgn(getRelDegrees(LEFT));
            rightSpeed = getRelDegrees(RIGHT)/getRelDegrees(LEFT)*leftSpeed;
        }
        else if (fabs(getRelDegrees(RIGHT))>fabs(getRelDegrees(LEFT)))
        {
            rightSpeed = 20*sgn(getRelDegrees(RIGHT));
            leftSpeed = getRelDegrees(LEFT)/getRelDegrees(RIGHT)*rightSpeed;
        }

        if (fabs(leftSpeed)<5)
        {
            leftSpeed = 0;
        }
        if (fabs(rightSpeed)<5)
        {
            rightSpeed = 0;
        }

        if (fabs(leftSpeed)>15)
        {
            leftSpeed = sgn(leftSpeed)*20;
        }

        if (fabs(rightSpeed)>15)
        {
            rightSpeed = sgn(rightSpeed)*20;
        }

        if (!(leftSpeed==0 && leftSpeed == 0))
        {
            playImmediateTone(100, 10);
            writeDebugStreamLine("moveSenseSimple(%d, %d, %s, 3, COLOR);", leftSpeed, rightSpeed, getColourName[getColor(3)]);
            resetRelative();
        }
    }

    // If the down button is pressed, write to the debug stream to line follow on the right edge with sensor 3
    else if (downPressed)
    {
        playImmediateTone(100, 10);
        writeDebugStreamLine("lineFollow(40, 30, %d, 50, -0.3, -0.23, 50, 3, RELDEG);", (getRelDegrees(LEFT)+getRelDegrees(RIGHT))/2);
        writeDebugStreamLine("resetRelative();");
        resetRelative();
    }
}

void page5()
{
    // When the up button is pressed, act as motor control to open the claw slowly
    if (getButtonPress(buttonUp))
    {
        setArmSpeed(CLAW, -15);
    }

    // When the down button is pressed, act as motor control to close the claw slowly
    else if (getButtonPress(buttonDown))
    {
        setArmSpeed(CLAW, 15);
    }

    // When the center button is pressed, write to the debug stream to move the claw to an absolute degrees
    else if (centerPressed)
    {
        playImmediateTone(100, 10);
        writeDebugStreamLine("moveArmAbs(60, 30, %d, 0.3, CLAW);", getArmDegreesAbs(CLAW));
    }

    // When no button is pressed, stop the claw from moving
    else
    {
        setArmSpeed(CLAW, 0);
    }
}

void page6()
{
    // If the up button is pressed, write to the debug stream to open the claw for seconds
    if (upPressed)
    {
        playImmediateTone(100, 10);
        writeDebugStreamLine("moveArm(100, 100, 1000, 0.01, CLAW, TIME);");
    }

    // If the down button is pressed, write to the debug stream to close the claw for seconds
    else if (downPressed)
    {
        playImmediateTone(100, 10);
        writeDebugStreamLine("moveArm(-100, -100, 1000, 0.01, CLAW, TIME);");
    }

    // If the center button is pressed, write to the debug stream to set the claw speed to close
    else if (centerPressed)
    {
        playImmediateTone(100, 10);
        writeDebugStreamLine("setArmSpeed(CLAW, -100);");
        writeDebugStreamLine("sleep(100);");
    }
}

void page7()
{
    // When the up button is pressed, act as motor control to move the lift up slowly
    if (getButtonPress(buttonUp))
    {
        setArmSpeed(LIFT, -15);
    }

    // When the down button is pressed, act as motor control to move the lift down slowly
    else if (getButtonPress(buttonDown))
    {
        setArmSpeed(LIFT, 15);
    }

    // When the center button is pressed, write to the debug stream to move the lift to an absolute degrees
    else if (centerPressed)
    {
        playImmediateTone(100, 10);
        writeDebugStreamLine("moveArmAbs(60, 30, %d, 0.3, LIFT);", getArmDegreesAbs(LIFT));
    }

    // When no button is pressed, stop the lift from moving
    else
    {
        setArmSpeed(LIFT, 0);
    }
}

void page8()
{
    // If the up button is pressed, write to the debug stream to move the lift up for seconds
    if (upPressed)
    {
        playImmediateTone(100, 10);
        writeDebugStreamLine("moveArm(-100, -100, 1000, 0.01, LIFT, TIME);");
    }

    // If the down button is pressed, write to the debug stream to move the lift down for seconds
    else if (downPressed)
    {
        playImmediateTone(100, 10);
        writeDebugStreamLine("moveArm(100, 100, 1000, 0.01, LIFT, TIME);");
    }
}

task main()
{
	// Any other setup code is done here
    setBlockBackButton(1);
	resetMotors();									// Resets motors
	setMotorBrakeMode(left, motorCoast);
	setMotorBrakeMode(right, motorCoast);
	setMotorBrakeMode(a, motorCoast);
	setMotorBrakeMode(d, motorBrake);

	clearDebugStream();
	writeDebugStreamLine("##################################################");

    textFile = fileOpenWrite("codeGenerationText.txt");

    while (!getButtonPress(buttonBack))
    {
        // This part of the code gets whether or not to use the button inputs, it only uses the button inputs when the button went from off to on
        rightPressed =  (getButtonPress(buttonRight) && !rightWasPressed);
        rightWasPressed = getButtonPress(buttonRight);

        leftPressed =  (getButtonPress(buttonLeft) && !leftWasPressed);
        leftWasPressed = getButtonPress(buttonLeft);

        upPressed =  (getButtonPress(buttonUp) && !upWasPressed);
        upWasPressed = getButtonPress(buttonUp);

        centerPressed =  (getButtonPress(buttonEnter) && !centerWasPressed);
        centerWasPressed = getButtonPress(buttonEnter);

        downPressed =  (getButtonPress(buttonDown) && !downWasPressed);
        downWasPressed = getButtonPress(buttonDown);

        // Changes the page variable to one higher when the right button is pressed
        if (rightPressed)
        {
            page = mod(page, 8)+1;
            playImmediateTone(100, 10);
        }

        // Changes the page variable to one lower when the left button is pressed
        if (leftPressed)
        {
            page = mod(page-2, 8)+1;
            playImmediateTone(100, 10);
        }

        // Does the display for page 1 and runs the code generation logic
        if (page == 1)
        {
            displayCenteredBigTextLine(3, "Moving Normal");
            displayCenteredTextLine(6, "Left Motor: %d", getRelDegrees(LEFT));
            displayCenteredTextLine(8, "Right Motor: %d", getRelDegrees(RIGHT));
            displayCenteredTextLine(10, "");
            page1();
        }

        // Does the display for page 2 and runs the code generation logic
        if (page == 2)
        {
            displayCenteredBigTextLine(3, "Line Squaring");
            displayCenteredTextLine(6, "");
            displayCenteredTextLine(8, "");
            displayCenteredTextLine(10, "");
            page2();
        }

        // Does the display for page 3 and runs the code generation logic
        if (page == 3)
        {
            displayCenteredBigTextLine(3, "Moving Sensor 2");
            displayCenteredTextLine(6, "Left Motor: %d", getRelDegrees(LEFT));
            displayCenteredTextLine(8, "Right Motor: %d", getRelDegrees(RIGHT));
            displayCenteredTextLine(10, "Sensor 2 Color: %s", getColourName[getColor(2)]);
            page3();
        }

        // Does the display for page 4 and runs the code generation logic
        if (page == 4)
        {
            displayCenteredBigTextLine(3, "Moving Sensor 3");
            displayCenteredTextLine(6, "Left Motor: %d", getRelDegrees(LEFT));
            displayCenteredTextLine(8, "Right Motor: %d", getRelDegrees(RIGHT));
            displayCenteredTextLine(10, "Sensor 3 Color: %s", getColourName[getColor(3)]);
            page4();
        }

        // Does the display for page 5 and runs the code generation logic
        if (page == 5)
        {
            displayCenteredBigTextLine(3, "Claw Moving");
            displayCenteredTextLine(6, "Claw Absolute Degrees: %0.2f", getArmDegreesAbs(CLAW));
            displayCenteredTextLine(8, "");
            displayCenteredTextLine(10, "");
            page5();
        }

        // Does the display for page 6 and runs the code generation logic
        if (page == 6)
        {
            displayCenteredBigTextLine(3, "Claw Seconds");
            displayCenteredTextLine(6, "");
            displayCenteredTextLine(8, "");
            displayCenteredTextLine(10, "");
            page6();
        }

        // Does the display for page 7 and runs the code generation logic
        if (page == 7)
        {
            displayCenteredBigTextLine(3, "Lift Moving");
            displayCenteredTextLine(6, "LIFT Absolute Degrees: %0.2f", getArmDegreesAbs(LIFT));
            displayCenteredTextLine(8, "");
            displayCenteredTextLine(10, "");
            page7();
        }

        // Does the display for page 8 and runs the code generation logic
        if (page == 8)
        {
            displayCenteredBigTextLine(3, "Lift Seconds");
            displayCenteredTextLine(6, "");
            displayCenteredTextLine(8, "");
            displayCenteredTextLine(10, "");
            page8();
        }

        sleep(1);
    }
    fileClose(textFile);
    setBlockBackButton(1);
}
