#pragma config(UserModel, "/setup-functions/ports_setup.h")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "setup-functions/setup.c"							// Contains all the setup code
#include "setup-functions/misc_functions.c" 				// Contains all the miscellaneous functions
#include "setup-functions/sensing_functions.c" 				// Contains all the functions for sensing
#include "setup-functions/new_movement_functions.c" 		// Contains all the base movement functions
#include "setup-functions/simple_movement_functions.c"		// COntains all the simple movement functions

#include "setup-functions/tasks.c"
#include "code.c"

int page = 1;
bool rightWasPressed = false;
bool leftWasPressed = false;
bool upWasPressed = false;
bool centerWasPressed = false;
bool downWasPressed = false;

bool rightPressed = false;
bool leftPressed = false;
bool upPressed = false;
bool centerPressed = false;
bool downPressed = false;

long textFile;

char toWrite[100] = "";

void writeToFile()
{
    fileWriteData(textFile, toWrite, strlen(toWrite));
    fileWriteChar(textFile, '\n');
}

void page1()
{
    // If the up button was pressed, line follow with both sensors for degrees
    if (upPressed)
    {
        playImmediateTone(100, 10);
        writeDebugStreamLine("lineFollowTwoSensor(40, defaultMinspeed, defaultMinspeed, %d, defaultAcc, defaultAcc, 0.2, 15, true, 2, 3, RELDEG);", (getRelDegrees(LEFT)+getRelDegrees(RIGHT))/2);
        sprintf(toWrite, "lineFollowTwoSensor(40, defaultMinspeed, defaultMinspeed, %d, defaultAcc, defaultAcc, 0.2, 15, true, 2, 3, RELDEG);", (getRelDegrees(LEFT)+getRelDegrees(RIGHT))/2);
        writeToFile();
        resetRelative();
    }

    // If the center button is pressed, write to the debug stream to move for relative degrees
    else if (centerPressed)
    {
        // Sets the motor speeds based on the degrees traveled
        int leftSpeed = 0;
        int rightSpeed = 0;
        if (fabs(getRelDegrees(LEFT))>fabs(getRelDegrees(RIGHT)))
        {
            leftSpeed = 50*sgn(getRelDegrees(LEFT));
            rightSpeed = getRelDegrees(RIGHT)/getRelDegrees(LEFT)*leftSpeed;
        }
        else if (fabs(getRelDegrees(RIGHT))>fabs(getRelDegrees(LEFT)))
        {
            rightSpeed = 50*sgn(getRelDegrees(RIGHT));
            leftSpeed = getRelDegrees(LEFT)/getRelDegrees(RIGHT)*rightSpeed;
        }

        if (fabs(leftSpeed)<10)
        {
            leftSpeed = 0;
        }
        if (fabs(rightSpeed)<10)
        {
            rightSpeed = 0;
        }

        if (fabs(leftSpeed)>30)
        {
            leftSpeed = sgn(leftSpeed)*50;
        }

        if (fabs(rightSpeed)>30)
        {
            rightSpeed = sgn(rightSpeed)*50;
        }

        // Based on the speeds and how close they are, it determines if you were trying to turn for a nice amount of degrees or go straight etc.
        if (!(leftSpeed == 0 && rightSpeed == 0))
        {
            playImmediateTone(100, 10);

            // Turning 1 motor with the right motor
            if (leftSpeed == 0)
            {
                float val = cmFromDeg(getRelDegrees(RIGHT)/2.0);

                // If it is close to a multiple of 90
                if (mod(angleFromCM(fabs(val)), 90) < 15 || mod(angleFromCM(fabs(val)), 90) > 75)
                {
                    writeDebugStreamLine("turn1MotorAccMinspeed(40, defaultMinspeed, defaultMinspeed, %d, defaultAcc, defaultAcc, true, RIGHT);", 90*round(angleFromCM(val)/90.0));
                    sprintf(toWrite, "turn1MotorAccMinspeed(40, defaultMinspeed, defaultMinspeed, %d, defaultAcc, defaultAcc, true, RIGHT);", 90*round(angleFromCM(val)/90.0));
                    writeToFile();
                }
                else
                {
                    writeDebugStreamLine("turn1MotorAccMinspeed(40, defaultMinspeed, defaultMinspeed, %d, defaultAcc, defaultAcc, true, RIGHT);", angleFromCM(val));
                    sprintf(toWrite, "turn1MotorAccMinspeed(40, defaultMinspeed, defaultMinspeed, %d, defaultAcc, defaultAcc, true, RIGHT);", angleFromCM(val));
                    writeToFile();
                }
            }

            // Turning 1 motor with the left motor
            else if (rightSpeed == 0)
            {
                float val = cmFromDeg(getRelDegrees(LEFT)/2.0);

                // If it is close to a multiple of 90
                if (mod(angleFromCM(fabs(val)), 90) < 15 || mod(angleFromCM(fabs(val)), 90) > 75)
                {
                    writeDebugStreamLine("turn1MotorAccMinspeed(40, defaultMinspeed, defaultMinspeed, %d, defaultAcc, defaultAcc, true, LEFT);", 90*round(angleFromCM(val)/90.0));
                    sprintf(toWrite, "turn1MotorAccMinspeed(40, defaultMinspeed, defaultMinspeed, %d, defaultAcc, defaultAcc, true, LEFT);", 90*round(angleFromCM(val)/90.0));
                    writeToFile();
                }
                else
                {
                    writeDebugStreamLine("turn1MotorAccMinspeed(40, defaultMinspeed, defaultMinspeed, %d, defaultAcc, defaultAcc, true, LEFT);", angleFromCM(val));
                    sprintf(toWrite, "turn1MotorAccMinspeed(40, defaultMinspeed, defaultMinspeed, %d, defaultAcc, defaultAcc, true, LEFT);", angleFromCM(val));
                    writeToFile();
                }
            }

            // Turning 2 motor
            else if (rightSpeed == -leftSpeed)
            {
                float val = cmFromDeg(getRelDegrees(LEFT));

                // If it is close to a multiple of 90
                if (mod(angleFromCM(fabs(val)), 90) < 15 || mod(angleFromCM(fabs(val)), 90) > 75)
                {
                    writeDebugStreamLine("turn2MotorAccMinspeed(20, defaultMinspeed, defaultMinspeed, %d, defaultAcc, defaultAcc, true);", 90*round(angleFromCM(val)/90.0));
                    sprintf(toWrite, "turn2MotorAccMinspeed(20, defaultMinspeed, defaultMinspeed, %d, defaultAcc, defaultAcc, true);", 90*round(angleFromCM(val)/90.0));
                    writeToFile();
                }
                else
                {
                    writeDebugStreamLine("turn2MotorAccMinspeed(20, defaultMinspeed, defaultMinspeed, %d, defaultAcc, defaultAcc, true);", angleFromCM(val));
                    sprintf(toWrite, "turn2MotorAccMinspeed(20, defaultMinspeed, defaultMinspeed, %d, defaultAcc, defaultAcc, true);", angleFromCM(val));
                    writeToFile();
                }
            }

            // Any other movement
            else
            {
                writeDebugStreamLine("moveNoSyncParam(%d, %d, defaultMinspeed, defaultMinspeed, %d, defaultAcc, defaultAcc, true, RELDEG);", leftSpeed, rightSpeed, max2(fabs(getRelDegrees(RIGHT)),fabs(getRelDegrees(LEFT))));
                sprintf(toWrite, "moveNoSyncParam(%d, %d, defaultMinspeed, defaultMinspeed, %d, defaultAcc, defaultAcc, true, RELDEG);", leftSpeed, rightSpeed, max2(fabs(getRelDegrees(RIGHT)),fabs(getRelDegrees(LEFT))));
                writeToFile();
            }
            resetRelative();
        }
    }

    // If the down button is pressed, write to the debug stream to wall square backwards
    else if (downPressed)
    {
        playImmediateTone(100, 10);
        writeDebugStreamLine("moveSimpleWallSquare(-100, -100, 1000, TIME);");
        writeDebugStreamLine("setSpeed(0, 0);");
        writeDebugStreamLine("resetRelative();");

        sprintf(toWrite, "moveSimpleWallSquare(-100, -100, 1000, TIME);");
        writeToFile();
        sprintf(toWrite, "setSpeed(0, 0);");
        writeToFile();
        sprintf(toWrite, "resetRelative();");
        writeToFile();
        resetRelative();
    }
}

void page2()
{
    // If the up button is pressed, write to the debug steam to line square on the front edge
    if (upPressed)
    {
        playImmediateTone(100, 10);
        writeDebugStreamLine("lineSquare(50, 50, 2, 3, -0.3, -0.03, -500, 2000);");
        writeDebugStreamLine("setSpeed(0, 0);");
        writeDebugStreamLine("sleep(100);");
        writeDebugStreamLine("resetRelative();");
        sprintf(toWrite, "lineSquare(50, 50, 2, 3, -0.3, -0.03, -500, 2000);");
        writeToFile();
        sprintf(toWrite, "setSpeed(0, 0);");
        writeToFile();
        sprintf(toWrite, "sleep(100);");
        writeToFile();
        sprintf(toWrite, "resetRelative();");
        writeToFile();
        resetRelative();
    }

    // If the down button is pressed, write to the debug stream to line square on the back edge
    else if (downPressed)
    {
        playImmediateTone(100, 10);
        writeDebugStreamLine("lineSquare(50, 50, 2, 3, 0.3, 0.03, 500, 2000);");
        writeDebugStreamLine("setSpeed(0, 0);");
        writeDebugStreamLine("sleep(100);");
        writeDebugStreamLine("resetRelative();");
        sprintf(toWrite, "lineSquare(50, 50, 2, 3, 0.3, 0.03, 500, 2000);");
        writeToFile();
        sprintf(toWrite, "setSpeed(0, 0);");
        writeToFile();
        sprintf(toWrite, "sleep(100);");
        writeToFile();
        sprintf(toWrite, "resetRelative();");
        writeToFile();
        resetRelative();
    }

    // If the center button is pressed, write to the debug steam to move until sensor 1 sees a color
    else if (centerPressed)
    {
        // Sets the motor speeds based on the degrees traveled
        int leftSpeed = 0;
        int rightSpeed = 0;
        if (fabs(getRelDegrees(LEFT))>fabs(getRelDegrees(RIGHT)))
        {
            leftSpeed = 20*sgn(getRelDegrees(LEFT));
            rightSpeed = getRelDegrees(RIGHT)/getRelDegrees(LEFT)*leftSpeed;
        }
        else if (fabs(getRelDegrees(RIGHT))>fabs(getRelDegrees(LEFT)))
        {
            rightSpeed = 20*sgn(getRelDegrees(RIGHT));
            leftSpeed = getRelDegrees(LEFT)/getRelDegrees(RIGHT)*rightSpeed;
        }

        if (fabs(leftSpeed)<5)
        {
            leftSpeed = 0;
        }
        if (fabs(rightSpeed)<5)
        {
            rightSpeed = 0;
        }

        if (fabs(leftSpeed)>15)
        {
            leftSpeed = sgn(leftSpeed)*20;
        }

        if (fabs(rightSpeed)>15)
        {
            rightSpeed = sgn(rightSpeed)*20;
        }

        if (!(leftSpeed==0 && leftSpeed == 0))
        {
            playImmediateTone(100, 10);
            writeDebugStreamLine("moveSenseOneSensorSimple(%d, %d, defaultMinspeed, true, 1, %s, COLOR);", leftSpeed, rightSpeed, getColourName[getColor(1)]);
            sprintf(toWrite, "moveSenseOneSensorSimple(%d, %d, defaultMinspeed, true, 1, %s, COLOR);", leftSpeed, rightSpeed, getColourName[getColor(1)]);
            writeToFile();
            resetRelative();
        }
    }
}

void page3()
{
    // If the up button is pressed, write to the debug stream to line follow on the left edge with sensor 2
    if (upPressed)
    {
        playImmediateTone(100, 10);
        writeDebugStreamLine("lineFollowOneSensor(40, defaultMinspeed, defaultMinspeed, %d, defaultAcc, defaultAcc, 0.4, 20, true, 2, 50, RELDEG);", (getRelDegrees(LEFT)+getRelDegrees(RIGHT))/2);
        sprintf(toWrite, "lineFollowOneSensor(40, defaultMinspeed, defaultMinspeed, %d, defaultAcc, defaultAcc, 0.4, 20, true, 2, 50, RELDEG);", (getRelDegrees(LEFT)+getRelDegrees(RIGHT))/2);
        writeToFile();
        resetRelative();
    }

    // If the center button is pressed, write to the debug steam to move until sensor 2 sees a color
    else if (centerPressed)
    {
        // Sets the motor speeds based on the degrees traveled
        int leftSpeed = 0;
        int rightSpeed = 0;
        if (fabs(getRelDegrees(LEFT))>fabs(getRelDegrees(RIGHT)))
        {
            leftSpeed = 20*sgn(getRelDegrees(LEFT));
            rightSpeed = getRelDegrees(RIGHT)/getRelDegrees(LEFT)*leftSpeed;
        }
        else if (fabs(getRelDegrees(RIGHT))>fabs(getRelDegrees(LEFT)))
        {
            rightSpeed = 20*sgn(getRelDegrees(RIGHT));
            leftSpeed = getRelDegrees(LEFT)/getRelDegrees(RIGHT)*rightSpeed;
        }

        if (fabs(leftSpeed)<5)
        {
            leftSpeed = 0;
        }
        if (fabs(rightSpeed)<5)
        {
            rightSpeed = 0;
        }

        if (fabs(leftSpeed)>15)
        {
            leftSpeed = sgn(leftSpeed)*20;
        }

        if (fabs(rightSpeed)>15)
        {
            rightSpeed = sgn(rightSpeed)*20;
        }

        if (!(leftSpeed==0 && leftSpeed == 0))
        {
            playImmediateTone(100, 10);
            writeDebugStreamLine("moveSenseOneSensorSimple(%d, %d, defaultMinspeed, true, 2, %s, COLOR);", leftSpeed, rightSpeed, getColourName[getColor(2)]);
            sprintf(toWrite, "moveSenseOneSensorSimple(%d, %d, defaultMinspeed, true, 2, %s, COLOR);", leftSpeed, rightSpeed, getColourName[getColor(2)]);
            writeToFile();
            resetRelative();
        }
    }

    // If the down button is pressed, write to the debug stream to line follow on the right edge with sensor 2
    else if (downPressed)
    {
        playImmediateTone(100, 10);
        writeDebugStreamLine("lineFollowOneSensor(40, defaultMinspeed, defaultMinspeed, %d, defaultAcc, defaultAcc, -0.4, -20, true, 2, 50, RELDEG);", (getRelDegrees(LEFT)+getRelDegrees(RIGHT))/2);
        sprintf(toWrite, "lineFollowOneSensor(40, defaultMinspeed, defaultMinspeed, %d, defaultAcc, defaultAcc, -0.4, -20, true, 2, 50, RELDEG);", (getRelDegrees(LEFT)+getRelDegrees(RIGHT))/2);
        writeToFile();
        resetRelative();
    }
}

void page4()
{
    // If the up button is pressed, write to the debug stream to line follow on the left edge with sensor 3
    if (upPressed)
    {
        playImmediateTone(100, 10);
        writeDebugStreamLine("lineFollowOneSensor(40, defaultMinspeed, defaultMinspeed, %d, defaultAcc, defaultAcc, 0.4, 20, true, 3, 50, RELDEG);", (getRelDegrees(LEFT)+getRelDegrees(RIGHT))/2);
        sprintf(toWrite, "lineFollowOneSensor(40, defaultMinspeed, defaultMinspeed, %d, defaultAcc, defaultAcc, 0.4, 20, true, 3, 50, RELDEG);", (getRelDegrees(LEFT)+getRelDegrees(RIGHT))/2);
        writeToFile();
        resetRelative();
    }

    // If the center button is pressed, write to the debug steam to move until sensor 3 sees a color
    else if (centerPressed)
    {
        // Sets the motor speeds based on the degrees traveled
        int leftSpeed = 0;
        int rightSpeed = 0;
        if (fabs(getRelDegrees(LEFT))>fabs(getRelDegrees(RIGHT)))
        {
            leftSpeed = 20*sgn(getRelDegrees(LEFT));
            rightSpeed = getRelDegrees(RIGHT)/getRelDegrees(LEFT)*leftSpeed;
        }
        else if (fabs(getRelDegrees(RIGHT))>fabs(getRelDegrees(LEFT)))
        {
            rightSpeed = 20*sgn(getRelDegrees(RIGHT));
            leftSpeed = getRelDegrees(LEFT)/getRelDegrees(RIGHT)*rightSpeed;
        }

        if (fabs(leftSpeed)<5)
        {
            leftSpeed = 0;
        }
        if (fabs(rightSpeed)<5)
        {
            rightSpeed = 0;
        }

        if (fabs(leftSpeed)>15)
        {
            leftSpeed = sgn(leftSpeed)*20;
        }

        if (fabs(rightSpeed)>15)
        {
            rightSpeed = sgn(rightSpeed)*20;
        }

        if (!(leftSpeed==0 && leftSpeed == 0))
        {
            playImmediateTone(100, 10);
            writeDebugStreamLine("moveSenseOneSensorSimple(%d, %d, defaultMinspeed, true, 3, %s, COLOR);", leftSpeed, rightSpeed, getColourName[getColor(3)]);
            sprintf(toWrite, "moveSenseOneSensorSimple(%d, %d, defaultMinspeed, true, 3, %s, COLOR);", leftSpeed, rightSpeed, getColourName[getColor(3)]);
            resetRelative();
            writeToFile();
        }
    }

    // If the down button is pressed, write to the debug stream to line follow on the right edge with sensor 3
    else if (downPressed)
    {
        playImmediateTone(100, 10);
        writeDebugStreamLine("lineFollowOneSensor(40, defaultMinspeed, defaultMinspeed, %d, defaultAcc, defaultAcc, -0.4, -20, true, 3, 50, RELDEG);", (getRelDegrees(LEFT)+getRelDegrees(RIGHT))/2);
        sprintf(toWrite, "lineFollowOneSensor(40, defaultMinspeed, defaultMinspeed, %d, defaultAcc, defaultAcc, -0.4, -20, true, 3, 50, RELDEG);", (getRelDegrees(LEFT)+getRelDegrees(RIGHT))/2);
        writeToFile();
        resetRelative();
    }
}

void page5()
{
    // When the up button is pressed, act as motor control to open the claw slowly
    if (getButtonPress(buttonUp))
    {
        setArmSpeed(CLAW, 15);
    }

    // When the down button is pressed, act as motor control to close the claw slowly
    else if (getButtonPress(buttonDown))
    {
        setArmSpeed(CLAW, -15);
    }

    // When the center button is pressed, write to the debug stream to move the claw to an absolute degrees
    else if (centerPressed)
    {
        playImmediateTone(100, 10);
        writeDebugStreamLine("moveArmAbs(50, defaultArmMinspeed, defaultArmMinspeed, %d, defaultAcc, defaultAcc, CLAW);", getArmDegreesAbs(CLAW));
        sprintf(toWrite, "moveArmAbs(50, defaultArmMinspeed, defaultArmMinspeed, %d, defaultAcc, defaultAcc, CLAW);", getArmDegreesAbs(CLAW));
        writeToFile();
    }

    // When no button is pressed, stop the claw from moving
    else
    {
        setArmSpeed(CLAW, 0);
    }
}

void page6()
{
    // If the up button is pressed, write to the debug stream to open the claw for seconds
    if (upPressed)
    {
        playImmediateTone(100, 10);
        writeDebugStreamLine("moveArmSimple(100, 1000, CLAW, TIME);");
        sprintf(toWrite, "moveArmSimple(100, 1000, CLAW, TIME);");
        writeToFile();
    }

    // If the down button is pressed, write to the debug stream to close the claw for seconds
    else if (downPressed)
    {
        playImmediateTone(100, 10);
        writeDebugStreamLine("moveArmSimple(-100, 1000, CLAW, TIME);");
        sprintf(toWrite, "moveArmSimple(-100, 1000, CLAW, TIME);");
        writeToFile();
    }

    // If the center button is pressed, write to the debug stream to set the claw speed to close
    else if (centerPressed)
    {
        playImmediateTone(100, 10);
        writeDebugStreamLine("setArmSpeed(CLAW, -100);");
        writeDebugStreamLine("sleep(100);");
        sprintf(toWrite, "setArmSpeed(CLAW, -100);");
        writeToFile();
        sprintf(toWrite, "sleep(100);");
        writeToFile();
    }
}

void page7()
{
    // When the up button is pressed, act as motor control to move the lift up slowly
    if (getButtonPress(buttonUp))
    {
        setArmSpeed(LIFT, 15);
    }

    // When the down button is pressed, act as motor control to move the lift down slowly
    else if (getButtonPress(buttonDown))
    {
        setArmSpeed(LIFT, -15);
    }

    // When the center button is pressed, write to the debug stream to move the lift to an absolute degrees
    else if (centerPressed)
    {
        playImmediateTone(100, 10);
        writeDebugStreamLine("moveArmAbs(50, defaultArmMinspeed, defaultArmMinspeed, %d, defaultAcc, defaultAcc, LIFT);", getArmDegreesAbs(LIFT));
        sprintf(toWrite, "moveArmAbs(50, defaultArmMinspeed, defaultArmMinspeed, %d, defaultAcc, defaultAcc, LIFT);", getArmDegreesAbs(LIFT));
        writeToFile();

    }

    // When no button is pressed, stop the lift from moving
    else
    {
        setArmSpeed(LIFT, 0);
    }
}

void page8()
{
    // If the up button is pressed, write to the debug stream to move the lift up for seconds
    if (upPressed)
    {
        playImmediateTone(100, 10);
        writeDebugStreamLine("moveArmSimple(100, 1000, LIFT, TIME);");
        sprintf(toWrite, "moveArmSimple(100, 1000, LIFT, TIME);");
        writeToFile();
    }

    // If the down button is pressed, write to the debug stream to move the lift down for seconds
    else if (downPressed)
    {
        playImmediateTone(100, 10);
        writeDebugStreamLine("moveArmSimple(-100, 1000, LIFT, TIME);");
        sprintf(toWrite, "moveArmSimple(-100, 1000, LIFT, TIME);");
        writeToFile();
    }
}

task main()
{
    // Resets the claw and lift
    setArmSpeed(LIFT, 100);
    sleep(400);
    setArmSpeed(LIFT, 0);
    moveArmSimple(100, 500, CLAW, TIME);
    resetArmAbs(CLAW);
    moveArmAbsSimple(100, clawDegreeOpen-10, CLAW);
    moveArmSimple(-100, 700, LIFT, TIME);
    resetArmAbs(LIFT);

	setArmSpeed(CLAW, 0);
	setArmSpeed(LIFT, 0);
    sleep(50);

    displayCenteredBigTextLine(3, "Check Sensor 1");
    getColor(1);
    displayCenteredBigTextLine(3, "Check Sensor 2");
    getColor(2);
    displayCenteredBigTextLine(3, "Check Sensor 3");
    getColor(3);

	// Any other setup code is done here
    setBlockBackButton(1);
	resetMotors();									// Resets motors
	setMotorBrakeMode(left, motorCoast);
	setMotorBrakeMode(right, motorCoast);

	clearDebugStream();
	writeDebugStreamLine("##################################################");

    textFile = fileOpenWrite("codeGenerationText.txt");

    while (!getButtonPress(buttonBack))
    {

        // This part of the code gets whether or not to use the button inputs, it only uses the button inputs when the button went from off to on
        rightPressed =  (getButtonPress(buttonRight) && !rightWasPressed);
        rightWasPressed = getButtonPress(buttonRight);

        leftPressed =  (getButtonPress(buttonLeft) && !leftWasPressed);
        leftWasPressed = getButtonPress(buttonLeft);

        upPressed =  (getButtonPress(buttonUp) && !upWasPressed);
        upWasPressed = getButtonPress(buttonUp);

        centerPressed =  (getButtonPress(buttonEnter) && !centerWasPressed);
        centerWasPressed = getButtonPress(buttonEnter);

        downPressed =  (getButtonPress(buttonDown) && !downWasPressed);
        downWasPressed = getButtonPress(buttonDown);

        // Changes the page variable to one higher when the right button is pressed
        if (rightPressed)
        {
            page = mod(page, 8)+1;
            playImmediateTone(100, 10);
        }

        // Changes the page variable to one lower when the left button is pressed
        if (leftPressed)
        {
            page = mod(page-2, 8)+1;
            playImmediateTone(100, 10);
        }

        // Does the display for page 1 and runs the code generation logic
        if (page == 1)
        {
            displayCenteredBigTextLine(3, "Moving Normal");
            displayCenteredTextLine(6, "Left Motor: %d", getRelDegrees(LEFT));
            displayCenteredTextLine(8, "Right Motor: %d", getRelDegrees(RIGHT));
            displayCenteredTextLine(10, "");
            page1();
        }

        // Does the display for page 2 and runs the code generation logic
        if (page == 2)
        {
            displayCenteredBigTextLine(3, "Line Squaring");
            displayCenteredTextLine(6, "");
            displayCenteredTextLine(8, "");
            displayCenteredTextLine(10, "");
            page2();
        }

        // Does the display for page 3 and runs the code generation logic
        if (page == 3)
        {
            displayCenteredBigTextLine(3, "Moving Sensor 2");
            displayCenteredTextLine(6, "Left Motor: %d", getRelDegrees(LEFT));
            displayCenteredTextLine(8, "Right Motor: %d", getRelDegrees(RIGHT));
            displayCenteredTextLine(10, "Sensor 2 Color: %s", getColourName[getColor(2)]);
            page3();
        }

        // Does the display for page 4 and runs the code generation logic
        if (page == 4)
        {
            displayCenteredBigTextLine(3, "Moving Sensor 3");
            displayCenteredTextLine(6, "Left Motor: %d", getRelDegrees(LEFT));
            displayCenteredTextLine(8, "Right Motor: %d", getRelDegrees(RIGHT));
            displayCenteredTextLine(10, "Sensor 3 Color: %s", getColourName[getColor(3)]);
            page4();
        }

        // Does the display for page 5 and runs the code generation logic
        if (page == 5)
        {
            displayCenteredBigTextLine(3, "Claw Moving");
            displayCenteredTextLine(6, "Claw Absolute Degrees: %0.2f", getArmDegreesAbs(CLAW));
            displayCenteredTextLine(8, "");
            displayCenteredTextLine(10, "");
            page5();
        }

        // Does the display for page 6 and runs the code generation logic
        if (page == 6)
        {
            displayCenteredBigTextLine(3, "Claw Seconds");
            displayCenteredTextLine(6, "");
            displayCenteredTextLine(8, "");
            displayCenteredTextLine(10, "");
            page6();
        }

        // Does the display for page 7 and runs the code generation logic
        if (page == 7)
        {
            displayCenteredBigTextLine(3, "Lift Moving");
            displayCenteredTextLine(6, "LIFT Absolute Degrees: %0.2f", getArmDegreesAbs(LIFT));
            displayCenteredTextLine(8, "");
            displayCenteredTextLine(10, "");
            page7();
        }

        // Does the display for page 8 and runs the code generation logic
        if (page == 8)
        {
            displayCenteredBigTextLine(3, "Lift Seconds");
            displayCenteredTextLine(6, "");
            displayCenteredTextLine(8, "");
            displayCenteredTextLine(10, "");
            page8();
        }

        sleep(1);
    }
    fileClose(textFile);
    setBlockBackButton(1);
}
