#pragma config(UserModel, "C:/Users/Vedan/OneDrive/Documents/WRO-Codebase-2/ports_setup.h")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "setup.c"
#include "misc_functions.c" 						// Contains all the miscellaneous functions
#include "sensing_functions.c" 						// Contains all the functions for sensing
#include "movement_functions.c" 					// Contains all the movement functions
int port = 0;

task main()
{
	// Any other setup code is done here
	resetMotors();									// Resets motors

    while (true)
    {
        if (port<4){
            // Color Sensor
            displayCenteredBigTextLine(0, "Port: %d", port);
            displayCenteredBigTextLine(1, "True Reflection: %d", getTrueReflection(port+1));
            displayCenteredBigTextLine(2, "Calibrated Reflection: %0.2f", getReflection(port+1));
            displayCenteredBigTextLine(3, "Color: %s", getName[getColor(port+1)]);
            displayCenteredBigTextLine(4, "Ambience: %d", getAmbient(port+1));
            displayCenteredBigTextLine(5, "Hue: %d", getHue(port+1));
            displayCenteredBigTextLine(6, "Saturation: %d", getSaturation(port+1));
            displayCenteredBigTextLine(7, "RGB: (%d, %d, %d)", getRed(port+1), getGreen(port+1), getBlue(port+1));
        }
        if (port>3){
            // Motor
        }

        if (getButtonPress(buttonRight))
        {
            port+=1;
        }
        else if (getButtonPress(buttonLeft))
        {
            port-=1;
        }
        port = mod(port, 8);
        flushButtonMessages();
        sleep(50);
    }
}
