#pragma config(UserModel, "/ports_setup.h")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "setup.c"
#include "misc_functions.c" 						// Contains all the miscellaneous functions
#include "sensing_functions.c" 						// Contains all the functions for sensing
#include "movement_functions.c" 					// Contains all the movement functions

task main()
{
	// Any other setup code is done here
	resetMotors();									// Resets motors
	setMotorBrakeMode(left, motorCoast);
	setMotorBrakeMode(right, motorCoast);
	setMotorBrakeMode(a, motorCoast);
	setMotorBrakeMode(d, motorBrake);

	clearDebugStream();
	writeDebugStreamLine("##################################################");
    int port = 0;
    int state = 0;
    bool pressed = true;
    while (true)
    {
        if (port<4){
            // Color Sensor
	        if (getButtonPress(buttonUp) && pressed)
	        {
                playImmediateTone(100, 10);
	            state-=1;
	        }
	        else if (getButtonPress(buttonDown) && pressed)
	        {
                playImmediateTone(100, 10);
	            state+=1;
	        }
     		state = mod(state, 8);
            displayCenteredBigTextLine(3, "Port: %d", port+1);
            switch (state){
            	case 0:
            		displayCenteredTextLine(6, "Calibrated Reflection: %0.2f", getReflection(port+1));
            		break;
            	case 1:
            		displayCenteredTextLine(6, "True Reflection: %d", getTrueReflection(port+1));
            		break;
            	case 2:
            		displayCenteredTextLine(6, "Color: %s", getColourName[getColor(port+1)]);
            		break;
            	case 3:
            		displayCenteredTextLine(6, "True Color: %s", getColourName[getTrueColor(port+1)]);
            		break;
            	case 4:
            		displayCenteredTextLine(6, "Ambience: %d", getAmbient(port+1));
            		break;
            	case 5:
            		displayCenteredTextLine(6, "Hue: %d", getHue(port+1));
            		break;
            	case 6:
            		displayCenteredTextLine(6, "Saturation: %d", getSaturation(port+1));
            		break;
            	default:
            		displayCenteredTextLine(6, "RGB: (%d, %d, %d)", getRed(port+1), getGreen(port+1), getBlue(port+1));
            }
            displayCenteredTextLine(7, "");
            displayCenteredTextLine(8, "");
        }
        if (port>3){
            displayCenteredBigTextLine(3, "Motor: %s", getMotorName[port-4]);
            if (port<6){
            	if (getButtonPress(buttonUp))
		        {
		            setSpeed((port-4==LEFT) ? 10 : 0, (port-4==RIGHT) ? 10 : 0);
		        }
		        else if (getButtonPress(buttonDown))
		        {
		            setSpeed((port-4==LEFT) ? -10 : 0, (port-4==RIGHT) ? -10 : 0);
		        }
		        else
		        {
		        	setSpeed(0, 0);
		        }

                if (getButtonPress(buttonEnter) && pressed && (fabs(getRelDegrees(LEFT))>0 || fabs(getRelDegrees(RIGHT))>0)){
                    playImmediateTone(100, 10);
                    // Code generation for drivetrain movement
                    if (fabs(getRelDegrees(LEFT))<10 && fabs(getRelDegrees(RIGHT))>10){
                        float val = cmFromDeg(getRelDegrees(RIGHT)/2.0);
                        if (mod(angleFromCM(fabs(val)), 90)<5 || mod(angleFromCM(fabs(val)), 90)>85){
                            writeDebugStreamLine("turn1Motor(%d, %d, RIGHT);", sgn(val)*50, 90*round(angleFromCM(val)/90.0));
                        }else{
                            writeDebugStreamLine("turn1Motor(%d, %d, RIGHT);", sgn(val)*50, angleFromCM(val));
                        }
                    }
                    else if (fabs(getRelDegrees(RIGHT))<10 && fabs(getRelDegrees(LEFT))>10){
                        float val = cmFromDeg(getRelDegrees(LEFT)/2.0);
                        if (mod(angleFromCM(fabs(val)), 90)<5 || mod(angleFromCM(fabs(val)), 90)>85){
                            writeDebugStreamLine("turn1Motor(%d, %d, LEFT);", sgn(val)*50, 90*round(angleFromCM(val)/90.0));
                        }else{
                            writeDebugStreamLine("turn1Motor(%d, %d, LEFT);", sgn(val)*50, angleFromCM(val));
                        }
                    }
                    else if (fabs(getRelDegrees(RIGHT))/fabs(getRelDegrees(LEFT))<1.15 && fabs(getRelDegrees(RIGHT))/fabs(getRelDegrees(LEFT))>0.85){
                        if (sgn(getRelDegrees(RIGHT)) != sgn(getRelDegrees(LEFT)))
                        {
                            // Turning synch code generation
                            float val = cmFromDeg(getRelDegrees(RIGHT));
                            if (mod(angleFromCM(fabs(val)), 90)<15 || mod(angleFromCM(fabs(val)), 90)>75){
                                writeDebugStreamLine("turn2Motor(25, %d);", -90*round(angleFromCM(val)/90.0));
                            }
                            else
                            {
                                writeDebugStreamLine("turn2Motor(25, %d);", angleFromCM(val));
                            }
                        }
                        else
                        {
                            writeDebugStreamLine("moveSimple(%d, %d, %d, RELDEG);", 50*sgn(getRelDegrees(RIGHT)), 50*sgn(getRelDegrees(LEFT)), (fabs(getRelDegrees(RIGHT))+fabs(getRelDegrees(LEFT)))/2);
                        }
                    }
                    else{
                        int lSpeed = 0;
                        int rSpeed = 0;
                        if (fabs(getRelDegrees(LEFT))>fabs(getRelDegrees(RIGHT))){
                            lSpeed = 50*sgn(getRelDegrees(LEFT));
                            rSpeed = getRelDegrees(RIGHT)/getRelDegrees(LEFT)*lSpeed;
                        }
                        else if (fabs(getRelDegrees(RIGHT))>fabs(getRelDegrees(LEFT))){
                            rSpeed = 50*sgn(getRelDegrees(RIGHT));
                            lSpeed = getRelDegrees(LEFT)/getRelDegrees(RIGHT)*rSpeed;
                        }

                        writeDebugStreamLine("moveSimple(%d, %d, %d, RELDEG);", lSpeed, rSpeed, max2(fabs(getRelDegrees(RIGHT)),fabs(getRelDegrees(LEFT))));
                    }
                    resetRelative();
                }

            	displayCenteredTextLine(6, "Relative Degrees: %0.2f", getRelDegrees(port-4));
            	displayCenteredTextLine(7, "Absolute Degrees: %0.2f", getAbsDegrees(port-4));
            	displayCenteredTextLine(8, "True Degrees: %0.2f", getTrueDegrees(port-4));
        	}else{
        		if (getButtonPress(buttonUp))
		        {
		            setArmSpeed(port-4, 10);
		        }
		        else if (getButtonPress(buttonDown))
		        {
		            setArmSpeed(port-4, -10);
		        }
		        else
		        {
		        	setArmSpeed(port-4, 0);
		        }
		        if (getButtonPress(buttonEnter) && pressed)
		        {
                    playImmediateTone(100, 10);
		        	if (port==6)
		        	{
                        writeDebugStreamLine("moveArmAbs(100, 15, %d, 0.01, LIFT);", getAbsDegrees(LIFT));
		        	}
		        	else
		        	{
		        		writeDebugStreamLine("moveArmAbs(100, 15, %d, 0.01, CLAW);", getAbsDegrees(CLAW));
		        	}
		        }
        		displayCenteredTextLine(6, "Relative Degrees: %0.2f", getArmDegrees(port-4));
            	displayCenteredTextLine(7, "Absolute Degrees: %0.2f", getArmDegreesAbs(port-4));
        		displayCenteredTextLine(8, "");
            }
        }

        if (getButtonPress(buttonRight) && pressed)
        {
            playImmediateTone(100, 10);
            port+=1;
        }
        else if (getButtonPress(buttonLeft) && pressed)
        {
            playImmediateTone(100, 10);
            port-=1;
        }

        port = mod(port, 8);
        if (!getButtonPress(buttonAny)){
            pressed = true;
        }else{
            pressed = false;
        }
        sleep(10);
    }
}
