#pragma config(UserModel, "/setup-functions/ports_setup.h")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool startedClose = false; // Variable to store which side the robot starts on, true if close, false if far
bool is115 = true;

// Importing files
#include "setup-functions/setup.c"							// Contains all the setup code
#include "setup-functions/misc_functions.c" 				// Contains all the miscellaneous functions
#include "setup-functions/sensing_functions.c" 				// Contains all the functions for sensing
#include "setup-functions/new_movement_functions.c" 		// Contains all the base movement functions
#include "setup-functions/simple_movement_functions.c"		// COntains all the simple movement functions

#include "setup-functions/tasks.c"
#include "code.c"
#include "temp_surprise_day.c"

//CODE:

task main()
{
	// Any other setup code is done here
	resetMotors();									// Resets motors
	clearTimer(T1);									// Clears the timer for timing the run

	// Runs all the zones here
    setArmSpeed(LIFT, 100);
    sleep(400);
    setArmSpeed(LIFT, 0);
    moveArmSimple(100, 500, CLAW, TIME);
    resetArmAbs(CLAW);
    moveArmAbsSimple(100, clawDegreeOpen-10, CLAW);
    moveArmSimple(-100, 700, LIFT, TIME);
    resetArmAbs(LIFT);
    moveArmAbsSimple(100, 100, LIFT);

	setArmSpeed(CLAW, 0);
	setArmSpeed(LIFT, 0);
    sleep(50);


    resetMotors();									// Resets motors
	setMotorBrakeMode(left, motorCoast);
	setMotorBrakeMode(right, motorCoast);
    bool pressedBefore = false;
    bool sensors = 0;
    while (true)
    {
        if (sensors == 0)
        {
            displayCenteredTextLine(2, "Sensor 1 Color: %s", getColourName[getColor(1)]);
            displayCenteredTextLine(6, "Sensor 2 Color: %s", getColourName[getColor(2)]);
            displayCenteredTextLine(10, "Sensor 3 Color: %s", getColourName[getColor(3)]);
            displayCenteredTextLine(4, "");
            displayCenteredTextLine(8, "");
            displayCenteredTextLine(12, "");
            displayCenteredTextLine(14, "");
            displayCenteredTextLine(16, "");
        }
        else if (sensors ==2)
        {
            displayCenteredTextLine(4, "");
            displayCenteredTextLine(2, "Lift Deg: %d", getArmDegreesAbs(LIFT));
            displayCenteredTextLine(12, "");
            displayCenteredTextLine(6, "Claw Deg: %d", getArmDegreesAbs(CLAW));
            displayCenteredTextLine(8, "");
            displayCenteredTextLine(10, "Left Deg: %d", getRelDegrees(LEFT));
            displayCenteredTextLine(16, "");
            displayCenteredTextLine(14, "Right Deg: %d", getRelDegrees(RIGHT));
        }
        else
        {
            displayCenteredTextLine(4, "Sensor 2 Refl: %d", getReflection(2));
            displayCenteredTextLine(8, "Sensor 4 Blue: %d", getBlue(4));
            displayCenteredTextLine(10, "Sensor 4 Green: %d", getGreen(4));
            displayCenteredTextLine(6, "Sensor 3 Refl: %d", getReflection(3));
            displayCenteredTextLine(2, "Sensor 1 Refl: %d", getReflection(1));
            displayCenteredTextLine(12, "");
            displayCenteredTextLine(14, "");
            displayCenteredTextLine(16, "");
        }

        if (getButtonPress(buttonEnter) && !pressedBefore){
            sensors = (sensors+1)%3;
            resetRelative();
        }
        pressedBefore = getButtonPress(buttonEnter);

        if (getButtonPress(buttonUp))
        {
            setArmSpeed(LIFT, 15);
        }
        else if (getButtonPress(buttonDown))
        {
            setArmSpeed(LIFT, -15);
        }
        else
        {
            setArmSpeed(LIFT, 0);
        }

        if (getButtonPress(buttonRight))
        {
            setArmSpeed(CLAW, 15);
        }
        else if (getButtonPress(buttonLeft))
        {
            setArmSpeed(CLAW, -15);
        }
        else
        {
            setArmSpeed(CLAW, 0);
        }
        sleep(10);
    }
}
