#pragma config(UserModel, "C:/Users/Vedan/OneDrive/Documents/WRO-Codebase-2/ports_setup.h")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Importing files
#include "setup.c"									// Contains all the setup code
#include "misc_functions.c" 						// Contains all the miscellaneous functions
#include "sensing_functions.c" 						// Contains all the functions for sensing
#include "movement_functions.c" 					// Contains all the movement functions

//CODE:

task main()
{
	clearDebugStream();

	// Any other setup code is done here
	resetMotors();									// Resets motors
	clearTimer(T1);									// Clears the timer for timing the run
	//startTask(odometry);							// Starts the odometry loop
	//startTask(music);								// Starts the music playing

	// Runs all the zones here
	//turn2Motor(25, 90);
	//moveSimple(50, 50, 20, RELCM);
	moveArm(-50, 10, 160, 0.3, CLAW, RELDEG);
	moveArmAbs(50, 10, 0, 0.3, CLAW);
	return;
	move(-50, 50, 10, 1500, 0.3, 3, 0, TIME);
	move(50, -50, 10, 1500, 0.3, 3, 0, TIME);
	move(-50, -50, 10, 1500, 0.3, 3, 0, TIME);
	move(50, 50, 10, 1500, 0.3, 3, 0, TIME);
	move(-50, 0, 10, 1500, 0.3, 3, 0, TIME);
	move(50, 0, 10, 1500, 0.3, 3, 0, TIME);
	move(0, 50, 10, 1500, 0.3, 3, 0, TIME);
	move(0, -50, 10, 1500, 0.3, 3, 0, TIME);

	move(-50, 20, 10, 1500, 0.3, 3, 0, TIME);
	move(50, -20, 10, 1500, 0.3, 3, 0, TIME);
	move(-20, 50, 10, 1500, 0.3, 3, 0, TIME);
	move(20, -50, 10, 1500, 0.3, 3, 0, TIME);
	move(-50, -20, 10, 1500, 0.3, 3, 0, TIME);
	move(50, 20, 10, 1500, 0.3, 3, 0, TIME);
	move(-20, -50, 10, 1500, 0.3, 3, 0, TIME);
	move(20, 50, 10, 1500, 0.3, 3, 0, TIME);

	writeDebugStream("%f %f\n", getRelDegrees(LEFT), getRelDegrees(RIGHT));


	// Time display after the challenge is finished
	displayCenteredBigTextLine(5, "%0.2f", (time100(T1)/10.0));
	sleep(10000);

	// Sound after the challenge is finished
	if (time100(T1)>1200)
	{
		playSound(soundDownwardTones);				// Play negative sound if the challenge took too long
	}
	else
	{
		playSound(soundUpwardTones);				// PLay positive sound if the challenge was in time
	}

	stopAllTasks(); 								// Stops all the tasks (Music and odometry)

	sleep(10000);

}
