#pragma config(UserModel, "/ports_setup.h")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool startedClose = false; // Variable to store which side the robot starts on, true if close, false if far
bool skipGreenBlueStack = true; // Variable to store if we are skipping the green and blue stack

// Importing files
#include "setup.c"									// Contains all the setup code
#include "misc_functions.c" 						// Contains all the miscellaneous functions
#include "sensing_functions.c" 						// Contains all the functions for sensing
#include "movement_functions.c" 					// Contains all the movement functions

#include "code.c"
#include "surprise_challenge.c"

//CODE:

task main()
{
	// Any other setup code is done here
	resetMotors();									// Resets motors
	clearTimer(T1);									// Clears the timer for timing the run

	// Runs all the zones here
	code();
	surpriseChallenge();

	// Time display after the challenge is finished
	displayCenteredBigTextLine(5, "%0.2f", (time100(T1)/10.0));

	// Sound after the challenge is finished
	if (time100(T1)>1200)
	{
		playSound(soundDownwardTones);				// Play negative sound if the challenge took too long
	}
	else
	{
		playSound(soundUpwardTones);				// PLay positive sound if the challenge was in time
	}

	sleep(10000);

	stopAllTasks();
}
