#pragma config(UserModel, "/headers/ports_setup.h")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool startedClose = false; // Variable to store which side the robot starts on, true if close, false if far
bool is115 = true;

// Importing files
#include "scripts/setup.c"							// Contains all the setup code
#include "scripts/misc_functions.c" 				// Contains all the miscellaneous functions
#include "scripts/sensing_functions.c" 				// Contains all the functions for sensing
#include "scripts/movement_functions.c" 			// Contains all the base movement functions
#include "scripts/simple_movement_functions.c"		// COntains all the simple movement functions

#include "code/tasks.c"
#include "code/code.c"

//CODE:

task main()
{
	// Any other setup code is done here
	resetMotors();									// Resets motors
	clearTimer(T1);									// Clears the timer for timing the run

	// Runs all the zones here

	// while (1){
	// 	 displayCenteredBigTextLine(5, "G:%d, B:%d", getGreen(4), getBlue(4));
    //    //displayCenteredBigTextLine(5, "2:%d, 3:%d", getReflection(2), getReflection(3));
	// }

	displayCenteredBigTextLine(8, "Battery: %d%%", 100.0*(getBatteryVoltage()-minVoltage)/(maxVoltage-minVoltage));

	if (startedClose)
	{
		closeCode();
	}
	else
	{
		farCode();
	}

	// Time display after the challenge is finished
	displayCenteredBigTextLine(5, "Time: %0.2f", (time100(T1)/10.0));

	// Sound after the challenge is finished
	if (time100(T1)>1200)
	{
		playSound(soundDownwardTones);				// Play negative sound if the challenge took too long
	}
	else
	{
		playSound(soundUpwardTones);				// PLay positive sound if the challenge was in time
	}

	sleep(10000);

	stopAllTasks();
}
